version: "3.9"

services:
  app:
    build: .
    container_name: waste_management_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: waste_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wms
      MYSQL_USER: wmsuser
      MYSQL_PASSWORD: wmspass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./wms.sql:/docker-entrypoint-initdb.d/wms.sql

volumes:
  db_data:
